"""user accounts + per-user scoping

Revision ID: 2cae70d68811
Revises: 34f74d57f46b
Create Date: 2026-07-13 19:21:56.086849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cae70d68811'
down_revision: Union[str, Sequence[str], None] = '34f74d57f46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `users` may already exist because app startup runs create_all (which makes
    # missing *tables* but not the user_id *columns* below). Create it only if
    # absent so this migration is idempotent against create_all.
    bind = op.get_bind()
    if "users" not in sa.inspect(bind).get_table_names():
        op.create_table('users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('gym_state', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'gym_state', ['user_id'])
    op.create_foreign_key(None, 'gym_state', 'users', ['user_id'], ['id'])
    op.add_column('push_subscriptions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'push_subscriptions', 'users', ['user_id'], ['id'])
    op.add_column('reminder_dispatch_log', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('uq_dispatch_day_slot'), 'reminder_dispatch_log', type_='unique')
    op.create_index(op.f('ix_reminder_dispatch_log_user_id'), 'reminder_dispatch_log', ['user_id'], unique=False)
    op.create_unique_constraint('uq_dispatch_user_day_slot', 'reminder_dispatch_log', ['user_id', 'sent_on', 'slot'])
    op.create_foreign_key(None, 'reminder_dispatch_log', 'users', ['user_id'], ['id'])
    op.add_column('reminder_settings', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'reminder_settings', ['user_id'])
    op.create_foreign_key(None, 'reminder_settings', 'users', ['user_id'], ['id'])
    op.add_column('skincare_entries', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('skincare_entries_date_key'), 'skincare_entries', type_='unique')
    op.create_index(op.f('ix_skincare_entries_user_id'), 'skincare_entries', ['user_id'], unique=False)
    op.create_unique_constraint('uq_skincare_user_date', 'skincare_entries', ['user_id', 'date'])
    op.create_foreign_key(None, 'skincare_entries', 'users', ['user_id'], ['id'])
    op.add_column('workout_plans', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_workout_plans_user_id'), 'workout_plans', ['user_id'], unique=False)
    op.create_foreign_key(None, 'workout_plans', 'users', ['user_id'], ['id'])
    op.add_column('workout_sessions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'workout_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_column('workout_sessions', 'user_id')
    op.drop_constraint(None, 'workout_plans', type_='foreignkey')
    op.drop_index(op.f('ix_workout_plans_user_id'), table_name='workout_plans')
    op.drop_column('workout_plans', 'user_id')
    op.drop_constraint(None, 'skincare_entries', type_='foreignkey')
    op.drop_constraint('uq_skincare_user_date', 'skincare_entries', type_='unique')
    op.drop_index(op.f('ix_skincare_entries_user_id'), table_name='skincare_entries')
    op.create_unique_constraint(op.f('skincare_entries_date_key'), 'skincare_entries', ['date'], postgresql_nulls_not_distinct=False)
    op.drop_column('skincare_entries', 'user_id')
    op.drop_constraint(None, 'reminder_settings', type_='foreignkey')
    op.drop_constraint(None, 'reminder_settings', type_='unique')
    op.drop_column('reminder_settings', 'user_id')
    op.drop_constraint(None, 'reminder_dispatch_log', type_='foreignkey')
    op.drop_constraint('uq_dispatch_user_day_slot', 'reminder_dispatch_log', type_='unique')
    op.drop_index(op.f('ix_reminder_dispatch_log_user_id'), table_name='reminder_dispatch_log')
    op.create_unique_constraint(op.f('uq_dispatch_day_slot'), 'reminder_dispatch_log', ['sent_on', 'slot'], postgresql_nulls_not_distinct=False)
    op.drop_column('reminder_dispatch_log', 'user_id')
    op.drop_constraint(None, 'push_subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_column('push_subscriptions', 'user_id')
    op.drop_constraint(None, 'gym_state', type_='foreignkey')
    op.drop_constraint(None, 'gym_state', type_='unique')
    op.drop_column('gym_state', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
