"""baseline: full schema (skincare, reminders, push, gym)

Revision ID: 34f74d57f46b
Revises: 
Create Date: 2026-07-10 19:00:59.330570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f74d57f46b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_name'), 'equipment', ['name'], unique=True)
    op.create_table('muscle_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muscle_groups_name'), 'muscle_groups', ['name'], unique=True)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_table('reminder_dispatch_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sent_on', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sent_on', 'slot', name='uq_dispatch_day_slot')
    )
    op.create_table('reminder_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('morning_time', sa.Time(), nullable=False),
    sa.Column('evening_time', sa.Time(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skincare_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('face_wash', sa.Boolean(), nullable=False),
    sa.Column('vitamin_c', sa.Boolean(), nullable=False),
    sa.Column('moisturizer', sa.Boolean(), nullable=False),
    sa.Column('sunscreen', sa.Boolean(), nullable=False),
    sa.Column('lipcare', sa.Boolean(), nullable=False),
    sa.Column('cleanser', sa.Boolean(), nullable=False),
    sa.Column('evening_moisturizer', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('workout_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('primary_muscle_group_id', sa.UUID(), nullable=True),
    sa.Column('equipment_id', sa.UUID(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['primary_muscle_group_id'], ['muscle_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_equipment_id'), 'exercises', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=True)
    op.create_index(op.f('ix_exercises_primary_muscle_group_id'), 'exercises', ['primary_muscle_group_id'], unique=False)
    op.create_table('plan_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_days_plan_id'), 'plan_days', ['plan_id'], unique=False)
    op.create_table('gym_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active_plan_id', sa.UUID(), nullable=True),
    sa.Column('last_completed_day_id', sa.UUID(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['active_plan_id'], ['workout_plans.id'], ),
    sa.ForeignKeyConstraint(['last_completed_day_id'], ['plan_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_day_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=True),
    sa.Column('target_reps', sa.String(), nullable=True),
    sa.Column('target_rest_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['plan_day_id'], ['plan_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_exercises_exercise_id'), 'plan_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_plan_exercises_plan_day_id'), 'plan_exercises', ['plan_day_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_day_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_day_id'], ['plan_days.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_completed_at'), 'workout_sessions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_workout_sessions_plan_day_id'), 'workout_sessions', ['plan_day_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_status'), 'workout_sessions', ['status'], unique=False)
    op.create_table('session_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_exercises_exercise_id'), 'session_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_session_exercises_session_id'), 'session_exercises', ['session_id'], unique=False)
    op.create_table('session_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_exercise_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['session_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_sets_session_exercise_id'), 'session_sets', ['session_exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_sets_session_exercise_id'), table_name='session_sets')
    op.drop_table('session_sets')
    op.drop_index(op.f('ix_session_exercises_session_id'), table_name='session_exercises')
    op.drop_index(op.f('ix_session_exercises_exercise_id'), table_name='session_exercises')
    op.drop_table('session_exercises')
    op.drop_index(op.f('ix_workout_sessions_status'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_plan_day_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_completed_at'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_plan_exercises_plan_day_id'), table_name='plan_exercises')
    op.drop_index(op.f('ix_plan_exercises_exercise_id'), table_name='plan_exercises')
    op.drop_table('plan_exercises')
    op.drop_table('gym_state')
    op.drop_index(op.f('ix_plan_days_plan_id'), table_name='plan_days')
    op.drop_table('plan_days')
    op.drop_index(op.f('ix_exercises_primary_muscle_group_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_equipment_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_table('workout_plans')
    op.drop_table('skincare_entries')
    op.drop_table('reminder_settings')
    op.drop_table('reminder_dispatch_log')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_muscle_groups_name'), table_name='muscle_groups')
    op.drop_table('muscle_groups')
    op.drop_index(op.f('ix_equipment_name'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
