"""add hourly water reminder settings

Revision ID: 70168206a7fa
Revises: a8a5aba68433
Create Date: 2026-07-24 15:14:12.426241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70168206a7fa'
down_revision: Union[str, Sequence[str], None] = 'a8a5aba68433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('water_settings', sa.Column('reminders_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('water_settings', sa.Column('reminder_start_time', sa.Time(), nullable=False, server_default='09:00:00'))
    op.add_column('water_settings', sa.Column('reminder_end_time', sa.Time(), nullable=False, server_default='21:00:00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('water_settings', 'reminder_end_time')
    op.drop_column('water_settings', 'reminder_start_time')
    op.drop_column('water_settings', 'reminders_enabled')
    # ### end Alembic commands ###
