"""add food entries table

Revision ID: 911e6aab0187
Revises: 34d5beab8d2f
Create Date: 2026-07-31 15:30:19.289435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '911e6aab0187'
down_revision: Union[str, Sequence[str], None] = '34d5beab8d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_entries_logged_at'), 'food_entries', ['logged_at'], unique=False)
    op.create_index(op.f('ix_food_entries_user_id'), 'food_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping 'plan_days', 'workout_plans',
    # 'plan_exercises', and 'equipment' — pre-existing drift between this DB
    # and the gym models unrelated to the food module. Left untouched here;
    # that cleanup belongs in its own migration, not bundled with this one.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_entries_user_id'), table_name='food_entries')
    op.drop_index(op.f('ix_food_entries_logged_at'), table_name='food_entries')
    op.drop_table('food_entries')
    # ### end Alembic commands ###
