"""add image_url to muscle_groups

Revision ID: a8a5aba68433
Revises: 2cae70d68811
Create Date: 2026-07-23 19:21:05.802091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a5aba68433'
down_revision: Union[str, Sequence[str], None] = '2cae70d68811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('muscle_groups', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('muscle_groups', 'image_url')
    # ### end Alembic commands ###
